[project]
name = "comfyui-sox-effects"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "numpy>=2.4.1",
    "pillow>=12.1.0",
    "torch>=2.10.0",
    "torchaudio>=2.10.0",
]
