[project]
name = "ComfyUI_SoX_Effects"
version = "0.1.3"
description = "ComfyUI Nodes for SoX & TorchAudio.sox-effects"
requires-python = ">=3.13"
dependencies = [
    "numpy>=2.4.1",
    "pillow>=12.1.0",
    "torch>=2.10.0",
    "torchaudio>=2.10.0",
]
